//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organisation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int DeptId { get; set; }
        public Nullable<System.Guid> IDGUID { get; set; }
        public string Designation { get; set; }
        public string ManagerName { get; set; }
        public string EmployeeType { get; set; }
        public string Notes { get; set; }
        public string EmpImage { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
